"""Added CheckoutRequestID

Revision ID: 2ecb68b637dc
Revises: 36e95009b5a2
Create Date: 2025-09-07 21:29:00.692017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ecb68b637dc'
down_revision = '36e95009b5a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkout_request_id', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['checkout_request_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('checkout_request_id')

    # ### end Alembic commands ###
