"""uuid and id fields in order model

Revision ID: 3d0469732519
Revises: 
Create Date: 2025-08-06 13:52:08.164503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d0469732519'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column(
            'uuid',
            existing_type=sa.VARCHAR(length=36),
            type_=sa.UUID(),
            existing_nullable=True,
            postgresql_using="uuid::uuid"
        )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)

    # ### end Alembic commands ###
